services:
  selenium-hub:
    image: selenium/hub:4.16.1
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4443:4443"
      - "4442:4442"

  chrome:
    image: selenium/node-chrome:4.16.1
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "7900:7900"

  firefox:
    image: selenium/node-firefox:4.16.1
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "7901:7900"

  wiremock:
    image: wiremock/wiremock:3.10.0
    container_name: wiremock
    ports:
      - "${WIREMOCK_PORT}:${WIREMOCK_PORT}"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/files:/home/wiremock/__files
    environment:
      - WIREMOCK_OPTIONS=--port ${WIREMOCK_PORT} --verbose --global-response-templating --local-response-templating
