app {
    baseUrl = "https://webqa.mercdev.com"
    baseUrl = ${?APP_BASE_URL}
    userEmail = "placeholder@example.com"
    userEmail = ${?TEST_USER_EMAIL}
    password = "placeholder"
    password = ${?TEST_PASSWORD}
}

webdriver {
    browser = "chrome"
    browser = ${?WEBDRIVER_BROWSER}
    timeout = 10
    isRemote = false
    gridUrl = "http://localhost:4444/wd/hub"
    gridUrl = ${?SELENIUM_GRID_URL}
}

api {
    baseUrl = "https://webqa.mercdev.com/api/v1"
    timeout = 10
}

mock {
    wiremock {
        host = "localhost"
        port = 9999
        mappingsDir = "wiremock/mappings"
        filesDir = "wiremock/__files"
        options {
            verbose = true
            globalResponseTemplating = true
            localResponseTemplating = true
        }
    }
}
