name: 'Setup Java and Gradle Environments with caches'
description: 'Sets up Java, caches Gradle dependencies, and makes gradlew executable'
inputs:
  java-version:
    description: 'Java version to set up'
    required: false
    default: '17'
  distribution:
    description: 'Java distribution to use'
    required: false
    default: 'temurin'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        check-latest: false

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      id: gradle-cache
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        enableCrossOsArchive: false

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash
