name: Smoke Tests

on:
  push:
    branches: [ main, master, dev* ]
  workflow_dispatch:


permissions:
  contents: read
  actions: read
  checks: write

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java and Gradle Environment
        uses: ./.github/actions/java-setup

      - name: Run Detekt Security Check
        id: run-detekt
        run: ./gradlew detektSecurityCheck
        continue-on-error: true

      - name: Upload Detekt Reports
        uses: actions/upload-artifact@v4
        with:
          name: detekt-reports
          path: build/reports/detekt
          retention-days: 5

  api-tests:
    name: API Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java and Gradle Environment
        uses: ./.github/actions/java-setup

      - name: Run API Tests
        id: run-api-tests
        run: ./gradlew test --tests com.webqa.tests.api.SignUpAPITest
        #continue-on-error: true

      - name: Upload Build Directory
        if: failure() && steps.run-api-tests.outcome != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: api-build-directory
          path: build
          retention-days: 5

  ui-tests:
    name: UI Tests
    needs: api-tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java and Gradle Environment
        uses: ./.github/actions/java-setup

      - name: Start Selenium Grid
        run: docker compose up -d selenium-hub chrome

      - name: Check Docker containers
        run: |
          echo "Checking Docker containers..."
          docker ps
          docker logs selenium-hub
          CHROME_CONTAINER_ID=$(docker ps -q --filter "name=chrome")
          echo "Chrome container ID: $CHROME_CONTAINER_ID"
          docker logs "$CHROME_CONTAINER_ID"

      - name: Wait for Selenium Grid to be ready
        timeout-minutes: 2
        run: |
          echo "Waiting for Selenium Grid to initialize..."
          sleep 30
          echo "Checking Docker containers status:"
          docker ps
          echo "Continuing with tests..."

      - name: Run UI Tests
        id: run-ui-tests
        timeout-minutes: 20
        run: ./gradlew test --tests com.webqa.tests.ui.LoginTest --tests com.webqa.tests.ui.SignUpUITest -Dremote=true
        #continue-on-error: true

      - name: Upload Build Directory
        if: failure() && steps.run-ui-tests.outcome != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: ui-build-directory
          path: build
          retention-days: 5

      - name: Stop Selenium Grid
        if: always()
        run: docker compose down
