name: Smoke Tests

on:
  push:
    branches: [ main, master, dev* ]
  workflow_dispatch:

jobs:
  api-tests:
    name: API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        id: gradle-cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run API Tests
        id: run-api-tests
        run: ./gradlew test --tests com.webqa.tests.api.SignUpAPITest --tests com.webqa.tests.api.ProductApiTest
        #continue-on-error: true

      - name: Upload Build Directory
        if: failure() && steps.run-api-tests.outcome != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: api-build-directory
          path: build

  ui-tests:
    name: UI Tests
    needs: api-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        id: gradle-cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('docker-compose.yml') }}
          restore-keys: |
            docker-${{ runner.os }}-

      - name: Start Selenium Grid
        run: docker compose up -d selenium-hub chrome

      - name: Check Docker containers
        run: |
          echo "Checking Docker containers..."
          docker ps
          docker logs selenium-hub
          docker logs $(docker ps -q --filter "name=chrome")

      - name: Wait for Selenium Grid to be ready
        run: |
          echo "Waiting for Selenium Grid to be ready..."
          timeout=120
          while [ $timeout -gt 0 ]; do
            echo "Trying to connect to Selenium Grid..."
            if curl -v "http://localhost:4444/wd/hub/status" 2>&1 | grep -q "\"ready\":true" || curl -v "http://selenium-hub:4444/wd/hub/status" 2>&1 | grep -q "\"ready\":true"; then
              echo "Selenium Grid is ready!"
              break
            fi
            echo "Waiting for Selenium Grid... ($timeout seconds left)"
            sleep 10
            timeout=$((timeout - 10))
          done
          if [ $timeout -le 0 ]; then
            echo "Timed out waiting for Selenium Grid, but continuing anyway"
          fi

      - name: Run UI Tests
        id: run-ui-tests
        run: ./gradlew test --tests com.webqa.tests.ui.LoginTest --tests com.webqa.tests.ui.SignUpUITest -Dremote=true
        #continue-on-error: true

      - name: Upload Build Directory
        if: failure() && steps.run-ui-tests.outcome != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: ui-build-directory
          path: build

      - name: Stop Selenium Grid
        if: always()
        run: docker compose down
